#设置端口
server:
  port: 8000
#设置开发环境
spring:
  profiles:
    active: dev
#数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/shoppingmall
    type: com.alibaba.druid.pool.DruidDataSource
#thymeleaf配置
  thymeleaf:
    cache: false
#配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#配置逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0